name: Terraform Secrets/SQS
run-name: Deployment (${{ inputs.env }})
on:
  workflow_dispatch:
    inputs:
      env:
        description: Environment
        default: dev
        required: true
        type: choice
        options:
          - dev
          - qa
          - stage
          - prod
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}    
      TF_VAR_app_name: payment-auth-service
      TF_VAR_environment: ${{ inputs.env }}
      TF_VAR_primary_region: us-east-2
      TF_VAR_secondary_region: us-west-2
      TF_VAR_support_secondary: false
    defaults:
      run:
        shell: bash
        working-directory: module/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
          terraform_wrapper: false

      - name: Determine Backend Config
        id: backend-config
        shell: bash
        run: |
          echo "BACKEND_CONFIG=backend-${{ inputs.env }}.tfvars" >> $GITHUB_ENV
          echo "SECRECT_ENV_PREFIX=${{ format('SECRECT_ENV_PREFIX_{0}', inputs.env) }}" >> $GITHUB_ENV
          echo "AWS_ACCOUNT_ID=${{ format('AWS_ACCOUNT_ID_{0}', inputs.env) }}" >> $GITHUB_ENV
          echo "SUPPORT_SECONDARY=${{ format('SUPPORT_SECONDARY_{0}', inputs.env) }}" >> $GITHUB_ENV
 
      - name: Terraform Init
        run: terraform init -lock=false -backend-config="${{ env.BACKEND_CONFIG }}" -lock=false

      - name: Terraform Plan
        id: plan
        run: terraform plan -lock=false -out=tfplan

      - name: Terraform Apply
        env:
          TF_VAR_secret_env_prefix: ${{ secrets[env.SECRECT_ENV_PREFIX] }}
          TF_VAR_aws_account_id: ${{ secrets[env.AWS_ACCOUNT_ID] }}
          TF_VAR_support_secondary: ${{ secrets[env.SUPPORT_SECONDARY] }}
        run: terraform apply -lock=false -auto-approve tfplan
