name: Terraform Secrets/SQS
run-name: Deployment (${{ inputs.env }})
on:
  workflow_dispatch:
    inputs:
      env:
        description: Environment
        default: dev
        required: true
        type: choice
        options:
          - dev
          - qa
          - stage
          - prod
jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      VAR_FILE: environment/${{inputs.env}}/terraform.tfvars
      BACKEND_CONFIG: environment/${{inputs.env}}/backend.tfvars
    defaults:
      run:
        shell: bash
        working-directory: module/
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5
          terraform_wrapper: false
      - name: Terraform Init
        run: terraform init -backend-config=${{ env.BACKEND_CONFIG }} -var-file=${{ env.VAR_FILE }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
